# --------------------
# Define argument group of tasks.
# --------------------

# ==================== Alas ====================

Alas:
  menu: 'list'
  page: 'setting'
  tasks:
    Alas:
      - Emulator
      - EmulatorInfo
      - Error
      - Optimization
    Restart:
      - Scheduler

# ==================== Daily ====================

Daily:
  menu: 'list'
  page: 'setting'
  tasks:
    Dungeon:
      - Scheduler
      - Planner
      - Dungeon
      - DungeonSupport
      - DungeonStorage
      - TrailblazePower
    DailyQuest:
      - Scheduler
      - DailyStorage
    BattlePass:
      - Scheduler
      - BattlePassStorage
    Assignment:
      - Scheduler
      - Assignment
    DataUpdate:
      - Scheduler
      - ItemStorage
      - CloudStorage
    Freebies:
      - Scheduler
      - SupportReward

# ==================== Weekly ====================

Weekly:
  menu: 'list'
  page: 'setting'
  tasks:
    Weekly:
      - Scheduler
      - Weekly
      - DungeonSupport
    Rogue:
      - Scheduler
      - RogueWorld
      - RogueBlessing
      - RogueDebug
    Ornament:
      - Scheduler
      - Ornament
      - DungeonSupport
      - TrailblazePower

# ==================== Tool ====================

Tool:
  menu: 'list'
  page: 'tool'
  tasks:
    Daemon:
      - Daemon
    PlannerScan:
      - PlannerScan
